"""add document metadata

Revision ID: a6037dc0fa72
Revises: 9b66286f8b26
Create Date: 2026-06-23 22:00:22.993057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6037dc0fa72'
down_revision: Union[str, Sequence[str], None] = '9b66286f8b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('pages_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('words_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunks_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('document_type_confidence', sa.Float(), nullable=True))
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'document_type_confidence')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'chunks_count')
    op.drop_column('documents', 'words_count')
    op.drop_column('documents', 'pages_count')
    # ### end Alembic commands ###
